"""
Здесь находится перевод текста кнопок бота. Автоматически дёргается при отправке сообщения.
"""
buttons_translate = {
    "👀 Профиль": "👀 Profile",
    "👥 Гильдия": "👥 Guild",
    "📈Топы": "📈Tops",
    "🔖Связь с МИД": "🔖 Headquarters feedback",
    "🗂Обновления": "🗂Updates",
    "📰Инструкция": "📰Instruction",
    "↩️ Назад": "↩️ Back",
    "История гильдий": "Guild history",
    "Репорты": "Reports",
    "🔥Опыт": "🔥Experience",
    "⚙️Настройки": "⚙Settings",
    "🛒Уведомления о продаже": "🛒Sale notifications",
    "📦Изменения стока": "📦Stock changes",
    "📌Пинг на мобов": "📌Mobs pings",
    "Заместители": "Deputies",
    "Настройки": "Settings",
    "Список игроков": "Player list",
    "Покинуть гильдию": "Leave the guild",
    "Отключить выдачу ресурсов": "Disable withdraw resources",
    "Включить выдачу ресурсов": "Enable withdraw resources",
    "Отключить открепление пина": "Disable unpin",
    "Включить открепление пина": "Enable unpin",
    "Отключить напоминалку в 12": "Turn off reminder at 12PM",
    "Включить напоминалку в 12": "Turn on reminder at 12PM",
    "Отключить пинги к битве": "Disable pings for battle",
    "Включить пинги к битве": "Enable pings for battle",
    "⚔️Атака": "⚔️Attack",
    "🛡Защита": "🛡Defence",
    # "🔥Опыт": "🔥Experience",
    # "↩️ Назад": "↩️ Back",
    "👤Игроки": "👤Players",
    "👥Гильдии": "👥Guilds",
    "🖋Триггеры": "🖋Triggers",
    "📦Сток": "📦Stock",
    "↔️Указатели": "↔️Signs",
    "📓Гайды": "📓Guides",
    "⚗️Алхимик": "⚗Alchemist",
    "⚒Кузнец": "⚒Blacksmith",
    "📦Добытчик": "📦Collector",
    "🏹Лучник": "🏹Ranger",
    "⚔Рыцарь": "⚔Knight",
    "🛡Защитник": "🛡Sentinel",
    # "↩️ Назад": "↩️ Back",

    "Заступить на вахту": "Go on duty",
    "Покинуть вахту": "Leave duty",
    "Обратиться к 💂‍♂Стражам": "Talk to 💂‍♂Guardians",
    "↩️ Отмена": "↩️Cancel",
    "⛲️ Центральная площадь": "⛲️Central Square",
    "⛩ Врата замка": "⛩ Castle gates",
    "🎪 Казарма": "🎪 Barracks",
    "🏛 Тронный зал": "🏛Throne Room",
    "🎇Посмотреть на портреты": "🎇View portraits",
    "🏤Мандапа Славы": "🏤Hall of Fame",
    "🍵Чайная лига": "🍵Tea party",
    "Разведка": "Exploration",
    "Рыть котлован": "Dig a pit",
    "🎰Рулетка": "🎰Roulette",
    "🔸Сделать ставку": "🔸Place a bet",
    "🏆Игр выиграно": "🏆Games won",
    "🎰Игр сыграно": "🎰Games player",
    "🔘Выиграно": "🔘Won",
    "📈Топы в рулетке": "📈Roulette tops",
    "💲Магазин статусов": "💲Status shop",
    "🧳Контрабандист": "🧳Smuggler",

    "🌲Лесопилка": "🌲Sawmill",
    "⛰Каменоломня": "⛰Quarry",
    "💰Сокровищница": "💰Treasury",
    "🌲Дерево": "🌲Wood",
    "⛰Камень": "⛰Stone",
    "🏚Стройка": "🏚Construction",
    "🏚 Стройплощадка": "🏚 Construction Plate",
    "Попросить аудиенции у 👑Короля": "Ask for an audience with 👑King",
    "Обратиться к командному составу": "Contact the command staff",
    "👀 Посмотреть в зеркало": "👀 Look in the mirror",
    "👥 Посмотреть ведомость гильдии": "👥 View Guild List",
    "🔭 Башня ТехМаг наук": "🔭TechMag Science Tower",
    "📰Манускрипт": "📰Manuscript",
    "🧾История коммитов": "🧾Commits history",
    "🗂Архив объявлений": "🗂Announcements archive",
    "↔️ Подойти к указателям": "↔️ See the signs",

}

