
items = {
    "01": ["Champion sword", "Champion blade", 3],
    "02": ["Trident", "Trident blade", 3],
    "03": ["Hunter Bow", "Hunter Shaft", 3],
    "04": ["War hammer", "War hammer head", 3],
    "05": ["Hunter dagger", "Hunter blade", 3],
    "06": ["Order Armor", "Order Armor piece", 3],
    "07": ["Order Helmet", "Order Helmet fragment", 3],
    "08": ["Order Boots", "Order Boots part", 3],
    "09": ["Order Gauntlets", "Order Gauntlets part", 3],
    "10": ["Order shield", "Order shield part", 3],
    "11": ["Hunter Armor", "Hunter Armor part", 3],
    "12": ["Hunter Helmet", "Hunter Helmet fragment", 3],
    "13": ["Hunter Boots", "Hunter Boots part", 3],
    "14": ["Hunter Gloves", "Hunter Gloves part", 3],
    "15": ["Clarity Robe", "Clarity Robe piece", 3],
    "16": ["Clarity Circlet", "Clarity Circlet fragment", 3],
    "17": ["Clarity Shoes", "Clarity Shoes part", 3],
    "18": ["Clarity Bracers", "Clarity Bracers part", 3],
    "19": ["Thundersoul Sword", "Thundersoul blade", 5],
    "20": ["Doomblade sword", "Doomblade blade", 5],
    "21": ["Eclipse", "Eclipse blade", 5],
    "22": ["Guard’s Spear", "Guard's blade", 5],
    "23": ["King's Defender", "King's Defender blade", 5],
    "24": ["Raging Lance", "Raging Lance blade", 5],
    "25": ["Composite Bow", "Composite Bow shaft", 5],
    "26": ["Lightning Bow", "Lightning Bow shaft", 5],
    "27": ["Hailstorm Bow", "Hailstorm Bow shaft", 5],
    "28": ["Imperial Axe", "Imperial Axe head", 5],
    "29": ["Skull Crusher", "Skull Crusher head", 5],
    "30": ["Dragon Mace", "Dragon Mace head", 5],
    "31": ["Ghost dagger", "Ghost blade", 5],
    "32": ["Lion Knife", "Lion blade", 5],
    "33": ["Crusader Armor", "Crusader Armor piece", 5],
    "34": ["Crusader Helmet", "Crusader Helmet fragment", 5],
    "35": ["Crusader Boots", "Crusader Boots part", 5],
    "36": ["Crusader Gauntlets", "Crusader Gauntlets part", 5],
    "37": ["Crusader shield", "Crusader shield part", 5],
    "38": ["Royal Armor", "Royal Armor piece", 5],
    "39": ["Royal Helmet", "Royal Helmet fragment", 5],
    "40": ["Royal Boots", "Royal Boots part", 5],
    "41": ["Royal Gauntlets", "Royal Gauntlets part", 5],
    "42": ["Royal shield", "Royal shield part", 5],
    "43": ["Ghost Armor", "Ghost Armor part", 5],
    "44": ["Ghost Helmet", "Ghost Helmet fragment", 5],
    "45": ["Ghost Boots", "Ghost Boots part", 5],
    "46": ["Ghost Gloves", "Ghost Gloves part", 5],
    "47": ["Lion Armor", "Lion Armor part", 5],
    "48": ["Lion Helmet", "Lion Helmet fragment", 5],
    "49": ["Lion Boots", "Lion Boots part", 5],
    "50": ["Lion Gloves", "Lion Gloves part", 5],
    "51": ["Demon Robe", "Demon Robe piece", 5],
    "52": ["Demon Circlet", "Demon Circlet fragment", 5],
    "53": ["Demon Shoes", "Demon Shoes part", 5],
    "54": ["Demon Bracers", "Demon Bracers part", 5],
    "55": ["Divine Robe", "Divine Robe piece", 5],
    "56": ["Divine Circlet", "Divine Circlet fragment", 5],
    "57": ["Divine Shoes", "Divine Shoes part", 5],
    "58": ["Divine Bracers", "Divine Bracers part", 5],
    "59": ["Storm Cloak", "Storm Cloak part", 3],
    "60": ["Durable Cloak", "Durable Cloak part", 3],
    "61": ["Blessed Cloak", "Blessed Cloak part", 3],
    "78": ["Council Armor", "Council Armor part", 6],
    "79": ["Council Helmet", "Council Helmet part", 6],
    "80": ["Council Boots", "Council Boots part", 6],
    "81": ["Council Gauntlets", "Council Gauntlets part", 6],
    "82": ["Council Shield", "Council Shield part", 6],
    "83": ["Griffin Armor", "Griffin Armor part", 6],
    "84": ["Griffin Helmet", "Griffin Helmet part", 6],
    "85": ["Griffin Boots", "Griffin Boots part", 6],
    "86": ["Griffin Gloves", "Griffin Gloves part", 6],
    "87": ["Celestial Armor", "Celestial Armor part", 6],
    "88": ["Celestial Helmet", "Celestial Helmet part", 6],
    "89": ["Celestial Boots", "Celestial Boots part", 6],
    "90": ["Celestial Bracers", "Celestial Bracers part", 6],
    "91": ["Griffin Knife", "Griffin Knife part", 5],
    "92": ["Minotaur Sword", "Minotaur Sword part", 6],
    "93": ["Phoenix Sword", "Phoenix Sword part", 6],
    "94": ["Heavy Fauchard", "Heavy Fauchard part", 6],
    "95": ["Guisarme", "Guisarme part", 6],
    "96": ["Meteor Bow", "Meteor Bow part", 5],
    "97": ["Nightfall Bow", "Nightfall Bow part", 5],
    "98": ["Black Morningstar", "Black Morningstar part", 6],
    "99": ["Maiming Bulawa", "Maiming Bulawa part", 6],
    "100": ["Assault Cape", "Assault Cape part", 4],
    "101": ["Craftsman Apron", "Craftsman Apron part", 4],
    "102": ["Stoneskin Cloak", "Stoneskin Cloak part", 4]
}
