# @oldf4g property - do NOT copy, do NOT distribute

from collections import defaultdict

craft = defaultdict(dict)
craft['arrows'] = defaultdict(dict)
craft['arrows']['recipe']['iron ore'] = 1
craft['arrows']['recipe']['stick'] = 6
craft['arrows']['code'] = 505
craft['arrows']['type'] = 'craft'
craft['arrows']['guild'] = 0

craft['artisan frame'] = defaultdict(dict)
craft['artisan frame']['recipe']['bauxite'] = 5
craft['artisan frame']['recipe']['purified powder'] = 3
craft['artisan frame']['recipe']['steel mold'] = 1
craft['artisan frame']['code'] = 30
craft['artisan frame']['type'] = 'craft'
craft['artisan frame']['guild'] = 1

craft['artisan mold'] = defaultdict(dict)
craft['artisan mold']['recipe']['artisan frame'] = 2
craft['artisan mold']['recipe']['coke'] = 11
craft['artisan mold']['recipe']['magic stone'] = 2
craft['artisan mold']['recipe']['silver alloy'] = 5
craft['artisan mold']['code'] = 38
craft['artisan mold']['guild'] = 0
craft['artisan mold']['type'] = 'craft'

craft['blacksmith frame'] = defaultdict(dict)
craft['blacksmith frame']['recipe']['bauxite'] = 5
craft['blacksmith frame']['recipe']['purified powder'] = 3
craft['blacksmith frame']['recipe']['silver mold'] = 1
craft['blacksmith frame']['code'] = 29
craft['blacksmith frame']['guild'] = 1
craft['blacksmith frame']['type'] = 'craft'

craft['blacksmith mold'] = defaultdict(dict)
craft['blacksmith mold']['recipe']['blacksmith frame'] = 2
craft['blacksmith mold']['recipe']['coke'] = 11
craft['blacksmith mold']['recipe']['sapphire'] = 2
craft['blacksmith mold']['recipe']['silver alloy'] = 5
craft['blacksmith mold']['code'] = 37
craft['blacksmith mold']['guild'] = 0
craft['blacksmith mold']['type'] = 'craft'

craft['bone powder'] = defaultdict(dict)
craft['bone powder']['recipe']['bone'] = 4
craft['bone powder']['code'] = 21
craft['bone powder']['guild'] = 1
craft['bone powder']['type'] = 'simple'

craft['broad arrows pack'] = defaultdict(dict)
craft['broad arrows pack']['recipe']['bone powder'] = 2
craft['broad arrows pack']['recipe']['coke'] = 1
craft['broad arrows pack']['recipe']['iron ore'] = 3
craft['broad arrows pack']['recipe']['quality cloth'] = 1
craft['broad arrows pack']['recipe']['stick'] = 7
craft['broad arrows pack']['code'] = 515
craft['broad arrows pack']['guild'] = 0
craft['broad arrows pack']['type'] = 'craft'

craft['coke'] = defaultdict(dict)
craft['coke']['recipe']['charcoal'] = 3
craft['coke']['recipe']['coal'] = 3
craft['coke']['code'] = 23
craft['coke']['guild'] = 1
craft['coke']['type'] = 'simple'

craft['compound arrows pack'] = defaultdict(dict)
craft['compound arrows pack']['recipe']['bone powder'] = 1
craft['compound arrows pack']['recipe']['coke'] = 1
craft['compound arrows pack']['recipe']['iron ore'] = 2
craft['compound arrows pack']['recipe']['quality cloth'] = 1
craft['compound arrows pack']['recipe']['silver ore'] = 2
craft['compound arrows pack']['recipe']['stick'] = 7
craft['compound arrows pack']['code'] = 519
craft['compound arrows pack']['guild'] = 0
craft['compound arrows pack']['type'] = 'craft'

craft['cord'] = defaultdict(dict)
craft['cord']['recipe']['steel'] = 1
craft['cord']['recipe']['thread'] = 7
craft['cord']['code'] = 12
craft['cord']['guild'] = 1
craft['cord']['type'] = 'craft'

craft['crafted leather'] = defaultdict(dict)
craft['crafted leather']['recipe']['coal'] = 4
craft['crafted leather']['recipe']['cord'] = 1
craft['crafted leather']['recipe']['leather'] = 4
craft['crafted leather']['code'] = 35
craft['crafted leather']['guild'] = 1
craft['crafted leather']['type'] = 'craft'

craft['heavy arrows pack'] = defaultdict(dict)
craft['heavy arrows pack']['recipe']['coke'] = 2
craft['heavy arrows pack']['recipe']['iron ore'] = 7
craft['heavy arrows pack']['recipe']['quality cloth'] = 1
craft['heavy arrows pack']['recipe']['stick'] = 7
craft['heavy arrows pack']['code'] = 517
craft['heavy arrows pack']['guild'] = 0
craft['heavy arrows pack']['type'] = 'craft'

craft['leash'] = defaultdict(dict)
craft['leash']['recipe']['powder'] = 20
craft['leash']['recipe']['silver ore'] = 20
craft['leash']['recipe']['string'] = 10
craft['leash']['code'] = 502
craft['leash']['guild'] = 0
craft['leash']['type'] = 'craft'

craft['leather'] = defaultdict(dict)
craft['leather']['recipe']['pelt'] = 4
craft['leather']['code'] = 20
craft['leather']['guild'] = 1
craft['leather']['type'] = 'simple'

craft['metal plate'] = defaultdict(dict)
craft['metal plate']['recipe']['iron ore'] = 3
craft['metal plate']['recipe']['powder'] = 3
craft['metal plate']['recipe']['stick'] = 3
craft['metal plate']['code'] = 33
craft['metal plate']['guild'] = 1
craft['metal plate']['type'] = 'craft'

craft['metallic fiber'] = defaultdict(dict)
craft['metallic fiber']['recipe']['cord'] = 2
craft['metallic fiber']['recipe']['silver ore'] = 15
craft['metallic fiber']['type'] = 'craft'
craft['metallic fiber']['guild'] = 1
craft['metallic fiber']['code'] = 34

craft['purified powder'] = defaultdict(dict)
craft['purified powder']['recipe']['bone powder'] = 2
craft['purified powder']['recipe']['magic stone'] = 1
craft['purified powder']['recipe']['powder'] = 2
craft['purified powder']['code'] = 24
craft['purified powder']['guild'] = 1
craft['purified powder']['type'] = 'craft'

craft['quality cloth'] = defaultdict(dict)
craft['quality cloth']['recipe']['cloth'] = 11
craft['quality cloth']['recipe']['powder'] = 3
craft['quality cloth']['code'] = 36
craft['quality cloth']['type'] = 'craft'
craft['quality cloth']['guild'] = 0

craft['resurrection mix'] = defaultdict(dict)
craft['resurrection mix']['recipe']['bone'] = 50
craft['resurrection mix']['recipe']['magic stone'] = 3
craft['resurrection mix']['recipe']['pelt'] = 20
craft['resurrection mix']['recipe']['purified powder'] = 1
craft['resurrection mix']['code'] = 636
craft['resurrection mix']['type'] = 'craft'
craft['resurrection mix']['guild'] = 1

craft['rope'] = defaultdict(dict)
craft['rope']['recipe']['string'] = 1
craft['rope']['recipe']['thread'] = 4
craft['rope']['code'] = 31
craft['rope']['type'] = 'simple'
craft['rope']['guild'] = 1

craft['silver alloy'] = defaultdict(dict)
craft['silver alloy']['recipe']['purified powder'] = 1
craft['silver alloy']['recipe']['silver ore'] = 1
craft['silver alloy']['recipe']['steel'] = 1
craft['silver alloy']['code'] = 25
craft['silver alloy']['type'] = 'craft'
craft['silver alloy']['guild'] = 1

craft['silver arrows'] = defaultdict(dict)
craft['silver arrows']['recipe']['powder'] = 5
craft['silver arrows']['recipe']['silver ore'] = 5
craft['silver arrows']['recipe']['stick'] = 7
craft['silver arrows']['code'] = 512
craft['silver arrows']['type'] = 'craft'
craft['silver arrows']['guild'] = 0

craft['silver arrows pack'] = defaultdict(dict)
craft['silver arrows pack']['recipe']['powder'] = 5
craft['silver arrows pack']['recipe']['silver ore'] = 5
craft['silver arrows pack']['recipe']['stick'] = 7
craft['silver arrows pack']['code'] = 513
craft['silver arrows pack']['type'] = 'craft'
craft['silver arrows pack']['guild'] = 0

craft['silver frame'] = defaultdict(dict)
craft['silver frame']['recipe']['powder'] = 5
craft['silver frame']['recipe']['silver alloy'] = 3
craft['silver frame']['recipe']['silver ore'] = 5
craft['silver frame']['code'] = 32
craft['silver frame']['type'] = 'craft'
craft['silver frame']['guild'] = 1

craft['silver mold'] = defaultdict(dict)
craft['silver mold']['recipe']['coke'] = 2
craft['silver mold']['recipe']['silver ore'] = 2
craft['silver mold']['recipe']['string'] = 2
craft['silver mold']['code'] = 28
craft['silver mold']['type'] = 'craft'
craft['silver mold']['guild'] = 1

craft['steel'] = defaultdict(dict)
craft['steel']['recipe']['iron ore'] = 2
craft['steel']['recipe']['powder'] = 2
craft['steel']['code'] = 19
craft['steel']['type'] = 'simple'
craft['steel']['guild'] = 1

craft['steel arrows'] = defaultdict(dict)
craft['steel arrows']['recipe']['steel'] = 1
craft['steel arrows']['recipe']['stick'] = 4
craft['steel arrows']['code'] = 511
craft['steel arrows']['type'] = 'craft'
craft['steel arrows']['guild'] = 0

craft['steel mold'] = defaultdict(dict)
craft['steel mold']['recipe']['iron ore'] = 2
craft['steel mold']['recipe']['powder'] = 2
craft['steel mold']['recipe']['string'] = 2
craft['steel mold']['code'] = 27
craft['steel mold']['type'] = 'craft'
craft['steel mold']['guild'] = 1

craft['string'] = defaultdict(dict)
craft['string']['recipe']['stick'] = 3
craft['string']['code'] = 22
craft['string']['type'] = 'simple'
craft['string']['guild'] = 1

craft['torch'] = defaultdict(dict)
craft['torch']['recipe']['coke'] = 1
craft['torch']['recipe']['stick'] = 5
craft['torch']['code'] = 'tch'
craft['torch']['type'] = 'craft'
craft['torch']['guild'] = 0

craft['wooden shaft'] = defaultdict(dict)
craft['wooden shaft']['recipe']['powder'] = 1
craft['wooden shaft']['recipe']['stick'] = 5
craft['wooden shaft']['code'] = 14
craft['wooden shaft']['type'] = 'craft'
craft['wooden shaft']['guild'] = 1

craft['wrapping'] = defaultdict(dict)
craft['wrapping']['recipe']['cloth'] = 3
craft['wrapping']['recipe']['string'] = 3
craft['wrapping']['code'] = 501
craft['wrapping']['type'] = 'craft'
craft['wrapping']['code'] = 0

craft['champion sword'] = defaultdict(dict)
craft['champion sword']['recipe']['coke'] = 41
craft['champion sword']['recipe']['hardener'] = 3
craft['champion sword']['recipe']['metal plate'] = 41
craft['champion sword']['recipe']['ruby'] = 1
craft['champion sword']['recipe']['silver alloy'] = 27
craft['champion sword']['recipe']['steel mold'] = 3
craft['champion sword']['recipe']['champion sword recipe'] = 1
craft['champion sword']['recipe']['champion blade'] = 3
craft['champion sword']['code'] = 'w28'
craft['champion sword']['type'] = 'craft'
craft['champion sword']['guild'] = 1

craft['hunter bow'] = defaultdict(dict)
craft['hunter bow']['recipe']['coke'] = 41
craft['hunter bow']['recipe']['hardener'] = 3
craft['hunter bow']['recipe']['wooden shaft'] = 41
craft['hunter bow']['recipe']['ruby'] = 1
craft['hunter bow']['recipe']['silver alloy'] = 27
craft['hunter bow']['recipe']['steel mold'] = 3
craft['hunter bow']['recipe']['hunter bow recipe'] = 1
craft['hunter bow']['recipe']['hunter shaft'] = 3
craft['hunter bow']['code'] = 'w30'
craft['hunter bow']['type'] = 'craft'
craft['hunter bow']['guild'] = 1

craft['trident'] = defaultdict(dict)
craft['trident']['recipe']['coke'] = 41
craft['trident']['recipe']['hardener'] = 3
craft['trident']['recipe']['wooden shaft'] = 41
craft['trident']['recipe']['ruby'] = 1
craft['trident']['recipe']['silver alloy'] = 27
craft['trident']['recipe']['steel mold'] = 3
craft['trident']['recipe']['trident recipe'] = 1
craft['trident']['recipe']['trident blade'] = 3
craft['trident']['code'] = 'w29'
craft['trident']['type'] = 'craft'
craft['trident']['guild'] = 1

craft['war hammer'] = defaultdict(dict)
craft['war hammer']['recipe']['coke'] = 41
craft['war hammer']['recipe']['hardener'] = 3
craft['war hammer']['recipe']['metal plate'] = 41
craft['war hammer']['recipe']['ruby'] = 1
craft['war hammer']['recipe']['silver alloy'] = 27
craft['war hammer']['recipe']['steel mold'] = 3
craft['war hammer']['recipe']['war hammer recipe'] = 1
craft['war hammer']['recipe']['war hammer head'] = 3
craft['war hammer']['code'] = 'w31'
craft['war hammer']['type'] = 'craft'
craft['war hammer']['guild'] = 1

craft['hunter dagger'] = defaultdict(dict)
craft['hunter dagger']['recipe']['coke'] = 7
craft['hunter dagger']['recipe']['metal plate'] = 7
craft['hunter dagger']['recipe']['silver alloy'] = 15
craft['hunter dagger']['recipe']['steel mold'] = 1
craft['hunter dagger']['recipe']['hunter dagger recipe'] = 1
craft['hunter dagger']['recipe']['hunter blade'] = 3
craft['hunter dagger']['code'] = 'w32'
craft['hunter dagger']['type'] = 'craft'
craft['hunter dagger']['guild'] = 1

craft['hunter boots'] = defaultdict(dict)
craft['hunter boots']['recipe']['coke'] = 5
craft['hunter boots']['recipe']['leather'] = 12
craft['hunter boots']['recipe']['rope'] = 7
craft['hunter boots']['recipe']['silver mold'] = 1
craft['hunter boots']['recipe']['solvent'] = 1
craft['hunter boots']['recipe']['hunter boots recipe'] = 1
craft['hunter boots']['recipe']['hunter boots part'] = 3
craft['hunter boots']['code'] = 'a34'
craft['hunter boots']['type'] = 'craft'
craft['hunter boots']['guild'] = 1

craft['hunter gloves'] = defaultdict(dict)
craft['hunter gloves']['recipe']['coke'] = 5
craft['hunter gloves']['recipe']['leather'] = 12
craft['hunter gloves']['recipe']['rope'] = 7
craft['hunter gloves']['recipe']['silver mold'] = 1
craft['hunter gloves']['recipe']['solvent'] = 1
craft['hunter gloves']['recipe']['hunter gloves recipe'] = 1
craft['hunter gloves']['recipe']['hunter gloves part'] = 3
craft['hunter gloves']['code'] = 'a34'
craft['hunter gloves']['type'] = 'craft'
craft['hunter gloves']['guild'] = 1

craft['hunter armor'] = defaultdict(dict)
craft['hunter armor']['recipe']['coke'] = 9
craft['hunter armor']['recipe']['leather'] = 24
craft['hunter armor']['recipe']['rope'] = 12
craft['hunter armor']['recipe']['sapphire'] = 3
craft['hunter armor']['recipe']['silver mold'] = 3
craft['hunter armor']['recipe']['solvent'] = 5
craft['hunter armor']['recipe']['hunter armor recipe'] = 1
craft['hunter armor']['recipe']['hunter armor part'] = 3
craft['hunter armor']['code'] = 'a32'
craft['hunter armor']['type'] = 'craft'
craft['hunter armor']['guild'] = 1

craft['hunter helmet'] = defaultdict(dict)
craft['hunter helmet']['recipe']['coke'] = 7
craft['hunter helmet']['recipe']['leather'] = 18
craft['hunter helmet']['recipe']['rope'] = 9
craft['hunter helmet']['recipe']['sapphire'] = 1
craft['hunter helmet']['recipe']['silver mold'] = 2
craft['hunter helmet']['recipe']['solvent'] = 3
craft['hunter helmet']['recipe']['hunter helmet recipe'] = 1
craft['hunter helmet']['recipe']['hunter helmet fragment'] = 3
craft['hunter helmet']['code'] = 'a33'
craft['hunter helmet']['type'] = 'craft'
craft['hunter helmet']['guild'] = 1

craft['clarity shoes'] = defaultdict(dict)
craft['clarity shoes']['recipe']['coke'] = 3
craft['clarity shoes']['recipe']['leather'] = 7
craft['clarity shoes']['recipe']['rope'] = 5
craft['clarity shoes']['recipe']['sapphire'] = 1
craft['clarity shoes']['recipe']['silver mold'] = 1
craft['clarity shoes']['recipe']['solvent'] = 3
craft['clarity shoes']['recipe']['clarity shoes recipe'] = 1
craft['clarity shoes']['recipe']['clarity shoes part'] = 3
craft['clarity shoes']['code'] = 'a38'
craft['clarity shoes']['type'] = 'craft'
craft['clarity shoes']['guild'] = 1

craft['clarity bracers'] = defaultdict(dict)
craft['clarity bracers']['recipe']['coke'] = 3
craft['clarity bracers']['recipe']['leather'] = 7
craft['clarity bracers']['recipe']['rope'] = 5
craft['clarity bracers']['recipe']['sapphire'] = 1
craft['clarity bracers']['recipe']['silver mold'] = 1
craft['clarity bracers']['recipe']['solvent'] = 3
craft['clarity bracers']['recipe']['clarity bracers recipe'] = 1
craft['clarity bracers']['recipe']['clarity bracers part'] = 3
craft['clarity bracers']['code'] = 'a38'
craft['clarity bracers']['type'] = 'craft'
craft['clarity bracers']['guild'] = 1

craft['clarity robe'] = defaultdict(dict)
craft['clarity robe']['recipe']['coke'] = 9
craft['clarity robe']['recipe']['leather'] = 15
craft['clarity robe']['recipe']['rope'] = 12
craft['clarity robe']['recipe']['sapphire'] = 5
craft['clarity robe']['recipe']['silver mold'] = 3
craft['clarity robe']['recipe']['solvent'] = 7
craft['clarity robe']['recipe']['clarity robe recipe'] = 1
craft['clarity robe']['recipe']['clarity robe piece'] = 3
craft['clarity robe']['code'] = 'a36'
craft['clarity robe']['type'] = 'craft'
craft['clarity robe']['guild'] = 1

craft['clarity circlet'] = defaultdict(dict)
craft['clarity circlet']['recipe']['coke'] = 7
craft['clarity circlet']['recipe']['leather'] = 9
craft['clarity circlet']['recipe']['rope'] = 9
craft['clarity circlet']['recipe']['sapphire'] = 3
craft['clarity circlet']['recipe']['silver mold'] = 2
craft['clarity circlet']['recipe']['solvent'] = 5
craft['clarity circlet']['recipe']['clarity circlet recipe'] = 1
craft['clarity circlet']['recipe']['clarity circlet fragment'] = 3
craft['clarity circlet']['code'] = 'a37'
craft['clarity circlet']['type'] = 'craft'
craft['clarity circlet']['guild'] = 1

craft['order boots'] = defaultdict(dict)
craft['order boots']['recipe']['coke'] = 7
craft['order boots']['recipe']['metal plate'] = 9
craft['order boots']['recipe']['rope'] = 7
craft['order boots']['recipe']['silver mold'] = 1
craft['order boots']['recipe']['solvent'] = 1
craft['order boots']['recipe']['order boots recipe'] = 1
craft['order boots']['recipe']['order boots part'] = 3
craft['order boots']['code'] = 'a29'
craft['order boots']['type'] = 'craft'
craft['order boots']['guild'] = 1

craft['order gauntlets'] = defaultdict(dict)
craft['order gauntlets']['recipe']['coke'] = 7
craft['order gauntlets']['recipe']['metal plate'] = 9
craft['order gauntlets']['recipe']['rope'] = 7
craft['order gauntlets']['recipe']['silver mold'] = 1
craft['order gauntlets']['recipe']['solvent'] = 1
craft['order gauntlets']['recipe']['order gauntlets recipe'] = 1
craft['order gauntlets']['recipe']['order gauntlets part'] = 3
craft['order gauntlets']['code'] = 'a30'
craft['order gauntlets']['type'] = 'craft'
craft['order gauntlets']['guild'] = 1

craft['order armor'] = defaultdict(dict)
craft['order armor']['recipe']['coke'] = 9
craft['order armor']['recipe']['metal plate'] = 15
craft['order armor']['recipe']['rope'] = 12
craft['order armor']['recipe']['sapphire'] = 3
craft['order armor']['recipe']['silver mold'] = 3
craft['order armor']['recipe']['solvent'] = 5
craft['order armor']['recipe']['order armor recipe'] = 1
craft['order armor']['recipe']['order armor piece'] = 3
craft['order armor']['code'] = 'a27'
craft['order armor']['type'] = 'craft'
craft['order armor']['guild'] = 1

craft['order helmet'] = defaultdict(dict)
craft['order helmet']['recipe']['coke'] = 7
craft['order helmet']['recipe']['metal plate'] = 12
craft['order helmet']['recipe']['rope'] = 9
craft['order helmet']['recipe']['sapphire'] = 1
craft['order helmet']['recipe']['silver mold'] = 2
craft['order helmet']['recipe']['solvent'] = 3
craft['order helmet']['recipe']['order helmet recipe'] = 1
craft['order helmet']['recipe']['order helmet fragment'] = 3
craft['order helmet']['code'] = 'a28'
craft['order helmet']['type'] = 'craft'
craft['order helmet']['guild'] = 1

craft['order shield'] = defaultdict(dict)
craft['order shield']['recipe']['coke'] = 7
craft['order shield']['recipe']['metal plate'] = 7
craft['order shield']['recipe']['silver alloy'] = 15
craft['order shield']['recipe']['silver mold'] = 1
craft['order shield']['recipe']['order shield recipe'] = 1
craft['order shield']['recipe']['order shield part'] = 3
craft['order shield']['code'] = 'a28'
craft['order shield']['type'] = 'craft'
craft['order shield']['guild'] = 1

craft['eclipse'] = defaultdict(dict)
craft['eclipse']['recipe']['artisan frame'] = 5
craft['eclipse']['recipe']['coke'] = 61
craft['eclipse']['recipe']['hardener'] = 9
craft['eclipse']['recipe']['metal plate'] = 72
craft['eclipse']['recipe']['ruby'] = 3
craft['eclipse']['recipe']['silver frame'] = 11
craft['eclipse']['recipe']['eclipse recipe'] = 1
craft['eclipse']['recipe']['eclipse blade'] = 5
craft['eclipse']['code'] = 'w35'
craft['eclipse']['type'] = 'craft'
craft['eclipse']['guild'] = 1

craft['doomblade sword'] = defaultdict(dict)
craft['doomblade sword']['recipe']['artisan frame'] = 5
craft['doomblade sword']['recipe']['coke'] = 61
craft['doomblade sword']['recipe']['hardener'] = 9
craft['doomblade sword']['recipe']['metal plate'] = 72
craft['doomblade sword']['recipe']['ruby'] = 3
craft['doomblade sword']['recipe']['silver frame'] = 11
craft['doomblade sword']['recipe']['doomblade sword recipe'] = 1
craft['doomblade sword']['recipe']['doomblade blade'] = 5
craft['doomblade sword']['code'] = 'w34'
craft['doomblade sword']['type'] = 'craft'
craft['doomblade sword']['guild'] = 1

craft['thundersoul sword'] = defaultdict(dict)
craft['thundersoul sword']['recipe']['artisan frame'] = 5
craft['thundersoul sword']['recipe']['coke'] = 57
craft['thundersoul sword']['recipe']['hardener'] = 7
craft['thundersoul sword']['recipe']['metal plate'] = 68
craft['thundersoul sword']['recipe']['ruby'] = 3
craft['thundersoul sword']['recipe']['silver alloy'] = 33
craft['thundersoul sword']['recipe']['thundersoul sword recipe'] = 1
craft['thundersoul sword']['recipe']['thundersoul blade'] = 5
craft['thundersoul sword']['code'] = 'w33'
craft['thundersoul sword']['type'] = 'craft'
craft['thundersoul sword']['guild'] = 1

craft['lightning bow'] = defaultdict(dict)
craft['lightning bow']['recipe']['artisan frame'] = 5
craft['lightning bow']['recipe']['coke'] = 61
craft['lightning bow']['recipe']['hardener'] = 9
craft['lightning bow']['recipe']['ruby'] = 3
craft['lightning bow']['recipe']['silver frame'] = 11
craft['lightning bow']['recipe']['wooden shaft'] = 72
craft['lightning bow']['recipe']['lightning bow recipe'] = 1
craft['lightning bow']['recipe']['lightning bow shaft'] = 5
craft['lightning bow']['code'] = 'w40'
craft['lightning bow']['type'] = 'craft'
craft['lightning bow']['guild'] = 1

craft['composite bow'] = defaultdict(dict)
craft['composite bow']['recipe']['artisan frame'] = 5
craft['composite bow']['recipe']['coke'] = 57
craft['composite bow']['recipe']['hardener'] = 7
craft['composite bow']['recipe']['ruby'] = 3
craft['composite bow']['recipe']['silver alloy'] = 33
craft['composite bow']['recipe']['wooden shaft'] = 68
craft['composite bow']['recipe']['composite bow recipe'] = 1
craft['composite bow']['recipe']['composite bow shaft'] = 5
craft['composite bow']['code'] = 'w39'
craft['composite bow']['type'] = 'craft'
craft['composite bow']['guild'] = 1

craft['hailstorm bow'] = defaultdict(dict)
craft['hailstorm bow']['recipe']['artisan frame'] = 5
craft['hailstorm bow']['recipe']['coke'] = 61
craft['hailstorm bow']['recipe']['hardener'] = 9
craft['hailstorm bow']['recipe']['ruby'] = 3
craft['hailstorm bow']['recipe']['silver frame'] = 11
craft['hailstorm bow']['recipe']['wooden shaft'] = 72
craft['hailstorm bow']['recipe']['hailstorm bow recipe'] = 1
craft['hailstorm bow']['recipe']['hailstorm bow shaft'] = 5
craft['hailstorm bow']['code'] = 'w41'
craft['hailstorm bow']['type'] = 'craft'
craft['hailstorm bow']['guild'] = 1

craft['raging lance'] = defaultdict(dict)
craft['raging lance']['recipe']['artisan frame'] = 5
craft['raging lance']['recipe']['coke'] = 61
craft['raging lance']['recipe']['hardener'] = 9
craft['raging lance']['recipe']['ruby'] = 3
craft['raging lance']['recipe']['silver frame'] = 11
craft['raging lance']['recipe']['wooden shaft'] = 72
craft['raging lance']['recipe']['raging lance recipe'] = 1
craft['raging lance']['recipe']['raging lance blade'] = 5
craft['raging lance']['code'] = 'w38'
craft['raging lance']['type'] = 'craft'
craft['raging lance']['guild'] = 1

craft["king's defender"] = defaultdict(dict)
craft["king's defender"]["recipe"]["artisan frame"] = 5
craft["king's defender"]["recipe"]["coke"] = 61
craft["king's defender"]["recipe"]["hardener"] = 9
craft["king's defender"]["recipe"]["ruby"] = 3
craft["king's defender"]["recipe"]["silver frame"] = 11
craft["king's defender"]["recipe"]["wooden shaft"] = 72
craft["king's defender"]["recipe"]["king's defender recipe"] = 1
craft["king's defender"]["recipe"]["king's defender blade"] = 5
craft["king's defender"]["code"] = "w37"
craft["king's defender"]["type"] = "craft"
craft["king's defender"]["guild"] = 1

craft['skull crusher'] = defaultdict(dict)
craft['skull crusher']['recipe']['artisan frame'] = 5
craft['skull crusher']['recipe']['coke'] = 61
craft['skull crusher']['recipe']['hardener'] = 9
craft['skull crusher']['recipe']['ruby'] = 3
craft['skull crusher']['recipe']['silver frame'] = 11
craft['skull crusher']['recipe']['metal plate'] = 72
craft['skull crusher']['recipe']['skull crusher recipe'] = 1
craft['skull crusher']['recipe']['skull crusher head'] = 5
craft['skull crusher']['code'] = 'w43'
craft['skull crusher']['type'] = 'craft'
craft['skull crusher']['guild'] = 1

craft["guard's spear"] = defaultdict(dict)
craft["guard's spear"]["recipe"]["artisan frame"] = 5
craft["guard's spear"]["recipe"]["coke"] = 57
craft["guard's spear"]["recipe"]["hardener"] = 7
craft["guard's spear"]["recipe"]["ruby"] = 3
craft["guard's spear"]["recipe"]["silver alloy"] = 33
craft["guard's spear"]["recipe"]["wooden shaft"] = 68
craft["guard's spear"]["recipe"]["guard's spear recipe"] = 1
craft["guard's spear"]["recipe"]["guard's blade"] = 5
craft["guard's spear"]["code"] = "w36"
craft["guard's spear"]["type"] = "craft"
craft["guard's spear"]["guild"] = 1

craft['dragon mace'] = defaultdict(dict)
craft['dragon mace']['recipe']['artisan frame'] = 5
craft['dragon mace']['recipe']['coke'] = 61
craft['dragon mace']['recipe']['hardener'] = 9
craft['dragon mace']['recipe']['ruby'] = 3
craft['dragon mace']['recipe']['silver frame'] = 11
craft['dragon mace']['recipe']['metal plate'] = 72
craft['dragon mace']['recipe']['dragon mace recipe'] = 1
craft['dragon mace']['recipe']['dragon mace head'] = 5
craft['dragon mace']['code'] = 'w44'
craft['dragon mace']['type'] = 'craft'
craft['dragon mace']['guild'] = 1

craft['imperial axe'] = defaultdict(dict)
craft['imperial axe']['recipe']['artisan frame'] = 5
craft['imperial axe']['recipe']['coke'] = 57
craft['imperial axe']['recipe']['hardener'] = 7
craft['imperial axe']['recipe']['ruby'] = 3
craft['imperial axe']['recipe']['silver alloy'] = 33
craft['imperial axe']['recipe']['metal plate'] = 68
craft['imperial axe']['recipe']['imperial axe recipe'] = 1
craft['imperial axe']['recipe']['imperial axe head'] = 5
craft['imperial axe']['code'] = 'w42'
craft['imperial axe']['type'] = 'craft'
craft['imperial axe']['guild'] = 1

craft['lion knife'] = defaultdict(dict)
craft['lion knife']['recipe']['artisan frame'] = 3
craft['lion knife']['recipe']['coke'] = 15
craft['lion knife']['recipe']['hardener'] = 3
craft['lion knife']['recipe']['ruby'] = 1
craft['lion knife']['recipe']['silver alloy'] = 27
craft['lion knife']['recipe']['metal plate'] = 15
craft['lion knife']['recipe']['lion knife recipe'] = 1
craft['lion knife']['recipe']['lion blade'] = 5
craft['lion knife']['code'] = 'w46'
craft['lion knife']['type'] = 'craft'
craft['lion knife']['guild'] = 1

craft['ghost dagger'] = defaultdict(dict)
craft['ghost dagger']['recipe']['artisan frame'] = 3
craft['ghost dagger']['recipe']['coke'] = 15
craft['ghost dagger']['recipe']['hardener'] = 3
craft['ghost dagger']['recipe']['ruby'] = 1
craft['ghost dagger']['recipe']['silver alloy'] = 27
craft['ghost dagger']['recipe']['metal plate'] = 15
craft['ghost dagger']['recipe']['ghost dagger recipe'] = 1
craft['ghost dagger']['recipe']['ghost blade'] = 5
craft['ghost dagger']['code'] = 'w45'
craft['ghost dagger']['type'] = 'craft'
craft['ghost dagger']['guild'] = 1

craft['crusader shield'] = defaultdict(dict)
craft['crusader shield']['recipe']['blacksmith frame'] = 3
craft['crusader shield']['recipe']['coke'] = 15
craft['crusader shield']['recipe']['hardener'] = 3
craft['crusader shield']['recipe']['sapphire'] = 3
craft['crusader shield']['recipe']['silver alloy'] = 27
craft['crusader shield']['recipe']['metal plate'] = 15
craft['crusader shield']['recipe']['solvent'] = 7
craft['crusader shield']['recipe']['crusader shield recipe'] = 1
craft['crusader shield']['recipe']['crusader shield part'] = 5
craft['crusader shield']['code'] = 'a49'
craft['crusader shield']['type'] = 'craft'
craft['crusader shield']['guild'] = 1

craft['royal shield'] = defaultdict(dict)
craft['royal shield']['recipe']['blacksmith frame'] = 3
craft['royal shield']['recipe']['coke'] = 15
craft['royal shield']['recipe']['hardener'] = 3
craft['royal shield']['recipe']['sapphire'] = 3
craft['royal shield']['recipe']['silver alloy'] = 27
craft['royal shield']['recipe']['metal plate'] = 15
craft['royal shield']['recipe']['solvent'] = 7
craft['royal shield']['recipe']['royal shield recipe'] = 1
craft['royal shield']['recipe']['royal shield part'] = 5
craft['royal shield']['code'] = 'a54'
craft['royal shield']['type'] = 'craft'
craft['royal shield']['guild'] = 1

craft['lion helmet'] = defaultdict(dict)
craft['lion helmet']['recipe']['blacksmith frame'] = 3
craft['lion helmet']['recipe']['crafted leather'] = 14
craft['lion helmet']['recipe']['coke'] = 9
craft['lion helmet']['recipe']['rope'] = 12
craft['lion helmet']['recipe']['sapphire'] = 5
craft['lion helmet']['recipe']['solvent'] = 7
craft['lion helmet']['recipe']['lion helmet recipe'] = 1
craft['lion helmet']['recipe']['lion helmet fragment'] = 5
craft['lion helmet']['code'] = 'a56'
craft['lion helmet']['type'] = 'craft'
craft['lion helmet']['guild'] = 1

craft['ghost helmet'] = defaultdict(dict)
craft['ghost helmet']['recipe']['blacksmith frame'] = 3
craft['ghost helmet']['recipe']['crafted leather'] = 14
craft['ghost helmet']['recipe']['coke'] = 9
craft['ghost helmet']['recipe']['rope'] = 12
craft['ghost helmet']['recipe']['sapphire'] = 5
craft['ghost helmet']['recipe']['solvent'] = 7
craft['ghost helmet']['recipe']['ghost helmet recipe'] = 1
craft['ghost helmet']['recipe']['ghost helmet fragment'] = 5
craft['ghost helmet']['code'] = 'a66'
craft['ghost helmet']['type'] = 'craft'
craft['ghost helmet']['guild'] = 1

craft['crusader helmet'] = defaultdict(dict)
craft['crusader helmet']['recipe']['blacksmith frame'] = 3
craft['crusader helmet']['recipe']['metallic fiber'] = 27
craft['crusader helmet']['recipe']['coke'] = 9
craft['crusader helmet']['recipe']['rope'] = 12
craft['crusader helmet']['recipe']['sapphire'] = 5
craft['crusader helmet']['recipe']['solvent'] = 7
craft['crusader helmet']['recipe']['crusader helmet recipe'] = 1
craft['crusader helmet']['recipe']['crusader helmet fragment'] = 5
craft['crusader helmet']['code'] = 'a46'
craft['crusader helmet']['type'] = 'craft'
craft['crusader helmet']['guild'] = 1

craft['royal helmet'] = defaultdict(dict)
craft['royal helmet']['recipe']['blacksmith frame'] = 3
craft['royal helmet']['recipe']['metallic fiber'] = 27
craft['royal helmet']['recipe']['coke'] = 9
craft['royal helmet']['recipe']['rope'] = 12
craft['royal helmet']['recipe']['sapphire'] = 5
craft['royal helmet']['recipe']['solvent'] = 7
craft['royal helmet']['recipe']['royal helmet recipe'] = 1
craft['royal helmet']['recipe']['royal helmet fragment'] = 5
craft['royal helmet']['code'] = 'a51'
craft['royal helmet']['type'] = 'craft'
craft['royal helmet']['guild'] = 1

craft['demon circlet'] = defaultdict(dict)
craft['demon circlet']['recipe']['blacksmith frame'] = 3
craft['demon circlet']['recipe']['crafted leather'] = 8
craft['demon circlet']['recipe']['coke'] = 9
craft['demon circlet']['recipe']['rope'] = 12
craft['demon circlet']['recipe']['sapphire'] = 9
craft['demon circlet']['recipe']['solvent'] = 16
craft['demon circlet']['recipe']['demon circlet recipe'] = 1
craft['demon circlet']['recipe']['demon circlet fragment'] = 5
craft['demon circlet']['code'] = 'a64'
craft['demon circlet']['type'] = 'craft'
craft['demon circlet']['guild'] = 1

craft['divine circlet'] = defaultdict(dict)
craft['divine circlet']['recipe']['blacksmith frame'] = 3
craft['divine circlet']['recipe']['crafted leather'] = 8
craft['divine circlet']['recipe']['coke'] = 9
craft['divine circlet']['recipe']['rope'] = 12
craft['divine circlet']['recipe']['sapphire'] = 9
craft['divine circlet']['recipe']['solvent'] = 16
craft['divine circlet']['recipe']['divine circlet recipe'] = 1
craft['divine circlet']['recipe']['divine circlet fragment'] = 5
craft['divine circlet']['code'] = 'a68'
craft['divine circlet']['type'] = 'craft'
craft['divine circlet']['guild'] = 1

craft['lion armor'] = defaultdict(dict)
craft['lion armor']['recipe']['blacksmith frame'] = 5
craft['lion armor']['recipe']['crafted leather'] = 18
craft['lion armor']['recipe']['coke'] = 13
craft['lion armor']['recipe']['rope'] = 17
craft['lion armor']['recipe']['sapphire'] = 9
craft['lion armor']['recipe']['solvent'] = 15
craft['lion armor']['recipe']['lion armor recipe'] = 1
craft['lion armor']['recipe']['lion armor part'] = 5
craft['lion armor']['code'] = 'a59'
craft['lion armor']['type'] = 'craft'
craft['lion armor']['guild'] = 1

craft['ghost armor'] = defaultdict(dict)
craft['ghost armor']['recipe']['blacksmith frame'] = 5
craft['ghost armor']['recipe']['crafted leather'] = 18
craft['ghost armor']['recipe']['coke'] = 13
craft['ghost armor']['recipe']['rope'] = 17
craft['ghost armor']['recipe']['sapphire'] = 9
craft['ghost armor']['recipe']['solvent'] = 15
craft['ghost armor']['recipe']['ghost armor recipe'] = 1
craft['ghost armor']['recipe']['ghost armor part'] = 5
craft['ghost armor']['code'] = 'a55'
craft['ghost armor']['type'] = 'craft'
craft['ghost armor']['guild'] = 1

craft['crusader armor'] = defaultdict(dict)
craft['crusader armor']['recipe']['blacksmith frame'] = 5
craft['crusader armor']['recipe']['metallic fiber'] = 32
craft['crusader armor']['recipe']['coke'] = 13
craft['crusader armor']['recipe']['rope'] = 17
craft['crusader armor']['recipe']['sapphire'] = 9
craft['crusader armor']['recipe']['solvent'] = 15
craft['crusader armor']['recipe']['crusader armor recipe'] = 1
craft['crusader armor']['recipe']['crusader armor piece'] = 5
craft['crusader armor']['code'] = 'a45'
craft['crusader armor']['type'] = 'craft'
craft['crusader armor']['guild'] = 1

craft['demon robe'] = defaultdict(dict)
craft['demon robe']['recipe']['blacksmith frame'] = 5
craft['demon robe']['recipe']['crafted leather'] = 11
craft['demon robe']['recipe']['coke'] = 13
craft['demon robe']['recipe']['rope'] = 17
craft['demon robe']['recipe']['sapphire'] = 12
craft['demon robe']['recipe']['solvent'] = 21
craft['demon robe']['recipe']['demon robe recipe'] = 1
craft['demon robe']['recipe']['demon robe piece'] = 5
craft['demon robe']['code'] = 'a63'
craft['demon robe']['type'] = 'craft'
craft['demon robe']['guild'] = 1

craft['royal armor'] = defaultdict(dict)
craft['royal armor']['recipe']['blacksmith frame'] = 5
craft['royal armor']['recipe']['metallic fiber'] = 32
craft['royal armor']['recipe']['coke'] = 13
craft['royal armor']['recipe']['rope'] = 17
craft['royal armor']['recipe']['sapphire'] = 9
craft['royal armor']['recipe']['solvent'] = 15
craft['royal armor']['recipe']['royal armor recipe'] = 1
craft['royal armor']['recipe']['royal armor piece'] = 5
craft['royal armor']['code'] = 'a50'
craft['royal armor']['type'] = 'craft'
craft['royal armor']['guild'] = 1

craft['divine robe'] = defaultdict(dict)
craft['divine robe']['recipe']['blacksmith frame'] = 5
craft['divine robe']['recipe']['crafted leather'] = 11
craft['divine robe']['recipe']['coke'] = 13
craft['divine robe']['recipe']['rope'] = 17
craft['divine robe']['recipe']['sapphire'] = 12
craft['divine robe']['recipe']['solvent'] = 21
craft['divine robe']['recipe']['divine robe recipe'] = 1
craft['divine robe']['recipe']['divine robe piece'] = 5
craft['divine robe']['code'] = 'a67'
craft['divine robe']['type'] = 'craft'
craft['divine robe']['guild'] = 1

craft['lion gloves'] = defaultdict(dict)
craft['lion gloves']['recipe']['blacksmith frame'] = 1
craft['lion gloves']['recipe']['crafted leather'] = 11
craft['lion gloves']['recipe']['coke'] = 7
craft['lion gloves']['recipe']['rope'] = 9
craft['lion gloves']['recipe']['sapphire'] = 1
craft['lion gloves']['recipe']['solvent'] = 3
craft['lion gloves']['recipe']['lion gloves recipe'] = 1
craft['lion gloves']['recipe']['lion gloves part'] = 5
craft['lion gloves']['code'] = 'a62'
craft['lion gloves']['type'] = 'craft'
craft['lion gloves']['guild'] = 1

craft['ghost gloves'] = defaultdict(dict)
craft['ghost gloves']['recipe']['blacksmith frame'] = 1
craft['ghost gloves']['recipe']['crafted leather'] = 11
craft['ghost gloves']['recipe']['coke'] = 7
craft['ghost gloves']['recipe']['rope'] = 9
craft['ghost gloves']['recipe']['sapphire'] = 1
craft['ghost gloves']['recipe']['solvent'] = 3
craft['ghost gloves']['recipe']['ghost gloves recipe'] = 1
craft['ghost gloves']['recipe']['ghost gloves part'] = 5
craft['ghost gloves']['code'] = 'a58'
craft['ghost gloves']['type'] = 'craft'
craft['ghost gloves']['guild'] = 1

craft['crusader gauntlets'] = defaultdict(dict)
craft['crusader gauntlets']['recipe']['blacksmith frame'] = 1
craft['crusader gauntlets']['recipe']['metallic fiber'] = 21
craft['crusader gauntlets']['recipe']['coke'] = 7
craft['crusader gauntlets']['recipe']['rope'] = 9
craft['crusader gauntlets']['recipe']['sapphire'] = 1
craft['crusader gauntlets']['recipe']['solvent'] = 3
craft['crusader gauntlets']['recipe']['crusader gauntlets recipe'] = 1
craft['crusader gauntlets']['recipe']['crusader gauntlets part'] = 5
craft['crusader gauntlets']['code'] = 'a48'
craft['crusader gauntlets']['type'] = 'craft'
craft['crusader gauntlets']['guild'] = 1

craft['demon bracers'] = defaultdict(dict)
craft['demon bracers']['recipe']['blacksmith frame'] = 1
craft['demon bracers']['recipe']['crafted leather'] = 5
craft['demon bracers']['recipe']['coke'] = 7
craft['demon bracers']['recipe']['rope'] = 7
craft['demon bracers']['recipe']['sapphire'] = 5
craft['demon bracers']['recipe']['solvent'] = 7
craft['demon bracers']['recipe']['demon bracers recipe'] = 1
craft['demon bracers']['recipe']['demon bracers part'] = 5
craft['demon bracers']['code'] = 'a66'
craft['demon bracers']['type'] = 'craft'
craft['demon bracers']['guild'] = 1

craft['royal gauntlets'] = defaultdict(dict)
craft['royal gauntlets']['recipe']['blacksmith frame'] = 1
craft['royal gauntlets']['recipe']['metallic fiber'] = 21
craft['royal gauntlets']['recipe']['coke'] = 7
craft['royal gauntlets']['recipe']['rope'] = 9
craft['royal gauntlets']['recipe']['sapphire'] = 1
craft['royal gauntlets']['recipe']['solvent'] = 3
craft['royal gauntlets']['recipe']['royal gauntlets recipe'] = 1
craft['royal gauntlets']['recipe']['royal gauntlets part'] = 5
craft['royal gauntlets']['code'] = 'a53'
craft['royal gauntlets']['type'] = 'craft'
craft['royal gauntlets']['guild'] = 1

craft['divine bracers'] = defaultdict(dict)
craft['divine bracers']['recipe']['blacksmith frame'] = 1
craft['divine bracers']['recipe']['crafted leather'] = 5
craft['divine bracers']['recipe']['coke'] = 7
craft['divine bracers']['recipe']['rope'] = 7
craft['divine bracers']['recipe']['sapphire'] = 5
craft['divine bracers']['recipe']['solvent'] = 7
craft['divine bracers']['recipe']['divine bracers recipe'] = 1
craft['divine bracers']['recipe']['divine bracers part'] = 5
craft['divine bracers']['code'] = 'a70'
craft['divine bracers']['type'] = 'craft'
craft['divine bracers']['guild'] = 1

craft['lion boots'] = defaultdict(dict)
craft['lion boots']['recipe']['blacksmith frame'] = 1
craft['lion boots']['recipe']['crafted leather'] = 11
craft['lion boots']['recipe']['coke'] = 7
craft['lion boots']['recipe']['rope'] = 9
craft['lion boots']['recipe']['sapphire'] = 1
craft['lion boots']['recipe']['solvent'] = 3
craft['lion boots']['recipe']['lion boots recipe'] = 1
craft['lion boots']['recipe']['lion boots part'] = 5
craft['lion boots']['code'] = 'a61'
craft['lion boots']['type'] = 'craft'
craft['lion boots']['guild'] = 1

craft['ghost boots'] = defaultdict(dict)
craft['ghost boots']['recipe']['blacksmith frame'] = 1
craft['ghost boots']['recipe']['crafted leather'] = 11
craft['ghost boots']['recipe']['coke'] = 7
craft['ghost boots']['recipe']['rope'] = 9
craft['ghost boots']['recipe']['sapphire'] = 1
craft['ghost boots']['recipe']['solvent'] = 3
craft['ghost boots']['recipe']['ghost boots recipe'] = 1
craft['ghost boots']['recipe']['ghost boots part'] = 5
craft['ghost boots']['code'] = 'a57'
craft['ghost boots']['type'] = 'craft'
craft['ghost boots']['guild'] = 1

craft['crusader boots'] = defaultdict(dict)
craft['crusader boots']['recipe']['blacksmith frame'] = 1
craft['crusader boots']['recipe']['metallic fiber'] = 21
craft['crusader boots']['recipe']['coke'] = 7
craft['crusader boots']['recipe']['rope'] = 9
craft['crusader boots']['recipe']['sapphire'] = 1
craft['crusader boots']['recipe']['solvent'] = 3
craft['crusader boots']['recipe']['crusader boots recipe'] = 1
craft['crusader boots']['recipe']['crusader boots part'] = 5
craft['crusader boots']['code'] = 'a47'
craft['crusader boots']['type'] = 'craft'
craft['crusader boots']['guild'] = 1

craft['demon shoes'] = defaultdict(dict)
craft['demon shoes']['recipe']['blacksmith frame'] = 1
craft['demon shoes']['recipe']['crafted leather'] = 5
craft['demon shoes']['recipe']['coke'] = 7
craft['demon shoes']['recipe']['rope'] = 7
craft['demon shoes']['recipe']['sapphire'] = 5
craft['demon shoes']['recipe']['solvent'] = 7
craft['demon shoes']['recipe']['demon shoes recipe'] = 1
craft['demon shoes']['recipe']['demon shoes part'] = 5
craft['demon shoes']['code'] = 'a65'
craft['demon shoes']['type'] = 'craft'
craft['demon shoes']['guild'] = 1

craft['royal boots'] = defaultdict(dict)
craft['royal boots']['recipe']['blacksmith frame'] = 1
craft['royal boots']['recipe']['metallic fiber'] = 21
craft['royal boots']['recipe']['coke'] = 7
craft['royal boots']['recipe']['rope'] = 9
craft['royal boots']['recipe']['sapphire'] = 1
craft['royal boots']['recipe']['solvent'] = 3
craft['royal boots']['recipe']['royal boots recipe'] = 1
craft['royal boots']['recipe']['royal boots part'] = 5
craft['royal boots']['code'] = 'a52'
craft['royal boots']['type'] = 'craft'
craft['royal boots']['guild'] = 1

craft['divine shoes'] = defaultdict(dict)
craft['divine shoes']['recipe']['blacksmith frame'] = 1
craft['divine shoes']['recipe']['crafted leather'] = 5
craft['divine shoes']['recipe']['coke'] = 7
craft['divine shoes']['recipe']['rope'] = 7
craft['divine shoes']['recipe']['sapphire'] = 5
craft['divine shoes']['recipe']['solvent'] = 7
craft['divine shoes']['recipe']['divine shoes recipe'] = 1
craft['divine shoes']['recipe']['divine shoes part'] = 5
craft['divine shoes']['code'] = 'a69'
craft['divine shoes']['type'] = 'craft'
craft['divine shoes']['guild'] = 1

craft['storm cloak'] = defaultdict(dict)
craft['storm cloak']['recipe']['blacksmith frame'] = 1
craft['storm cloak']['recipe']['crafted leather'] = 5
craft['storm cloak']['recipe']['coke'] = 5
craft['storm cloak']['recipe']['rope'] = 3
craft['storm cloak']['recipe']['sapphire'] = 1
craft['storm cloak']['recipe']['solvent'] = 3
craft['storm cloak']['recipe']['storm cloak recipe'] = 1
craft['storm cloak']['recipe']['storm cloak part'] = 3
craft['storm cloak']['code'] = 'a71'
craft['storm cloak']['type'] = 'craft'
craft['storm cloak']['guild'] = 1

craft['durable cloak'] = defaultdict(dict)
craft['durable cloak']['recipe']['blacksmith frame'] = 1
craft['durable cloak']['recipe']['crafted leather'] = 5
craft['durable cloak']['recipe']['coke'] = 5
craft['durable cloak']['recipe']['rope'] = 3
craft['durable cloak']['recipe']['sapphire'] = 1
craft['durable cloak']['recipe']['solvent'] = 3
craft['durable cloak']['recipe']['durable cloak recipe'] = 1
craft['durable cloak']['recipe']['durable cloak part'] = 3
craft['durable cloak']['code'] = 'a72'
craft['durable cloak']['type'] = 'craft'
craft['durable cloak']['guild'] = 1

craft['blessed cloak'] = defaultdict(dict)
craft['blessed cloak']['recipe']['blacksmith frame'] = 1
craft['blessed cloak']['recipe']['crafted leather'] = 5
craft['blessed cloak']['recipe']['coke'] = 5
craft['blessed cloak']['recipe']['rope'] = 3
craft['blessed cloak']['recipe']['sapphire'] = 1
craft['blessed cloak']['recipe']['solvent'] = 3
craft['blessed cloak']['recipe']['blessed cloak recipe'] = 1
craft['blessed cloak']['recipe']['blessed cloak part'] = 3
craft['blessed cloak']['code'] = 'a73'
craft['blessed cloak']['type'] = 'craft'
craft['blessed cloak']['guild'] = 1

craft['minotaur sword'] = defaultdict(dict)
craft['minotaur sword']['recipe']['artisan mold'] = 3
craft['minotaur sword']['recipe']['coke'] = 119
craft['minotaur sword']['recipe']['hardener'] = 9
craft['minotaur sword']['recipe']['metal plate'] = 79
craft['minotaur sword']['recipe']['sapphire'] = 3
craft['minotaur sword']['recipe']['silver frame'] = 17
craft['minotaur sword']['recipe']['quality cloth'] = 3
craft['minotaur sword']['recipe']['minotaur sword recipe'] = 1
craft['minotaur sword']['recipe']['minotaur sword part'] = 6
craft['minotaur sword']['code'] = 'w92'
craft['minotaur sword']['type'] = 'craft'
craft['minotaur sword']['guild'] = 1

craft['phoenix sword'] = defaultdict(dict)
craft['phoenix sword']['recipe']['artisan mold'] = 3
craft['phoenix sword']['recipe']['coke'] = 119
craft['phoenix sword']['recipe']['hardener'] = 9
craft['phoenix sword']['recipe']['metal plate'] = 79
craft['phoenix sword']['recipe']['ruby'] = 3
craft['phoenix sword']['recipe']['silver frame'] = 10
craft['phoenix sword']['recipe']['quality cloth'] = 3
craft['phoenix sword']['recipe']['steel mold'] = 17
craft['phoenix sword']['recipe']['phoenix sword recipe'] = 1
craft['phoenix sword']['recipe']['phoenix sword part'] = 6
craft['phoenix sword']['code'] = 'w93'
craft['phoenix sword']['type'] = 'craft'
craft['phoenix sword']['guild'] = 1

craft['heavy fauchard'] = defaultdict(dict)
craft['heavy fauchard']['recipe']['artisan mold'] = 3
craft['heavy fauchard']['recipe']['coke'] = 111
craft['heavy fauchard']['recipe']['hardener'] = 6
craft['heavy fauchard']['recipe']['ruby'] = 3
craft['heavy fauchard']['recipe']['wooden shaft'] = 92
craft['heavy fauchard']['recipe']['silver frame'] = 18
craft['heavy fauchard']['recipe']['quality cloth'] = 3
craft['heavy fauchard']['recipe']['heavy fauchard recipe'] = 1
craft['heavy fauchard']['recipe']['heavy fauchard part'] = 6
craft['heavy fauchard']['code'] = 'w94'
craft['heavy fauchard']['type'] = 'craft'
craft['heavy fauchard']['guild'] = 1

craft['guisarme'] = defaultdict(dict)
craft['guisarme']['recipe']['artisan mold'] = 3
craft['guisarme']['recipe']['coke'] = 111
craft['guisarme']['recipe']['hardener'] = 9
craft['guisarme']['recipe']['wooden shaft'] = 92
craft['guisarme']['recipe']['sapphire'] = 3
craft['guisarme']['recipe']['silver frame'] = 7
craft['guisarme']['recipe']['quality cloth'] = 3
craft['guisarme']['recipe']['steel mold'] = 39
craft['guisarme']['recipe']['guisarme recipe'] = 1
craft['guisarme']['recipe']['guisarme part'] = 6
craft['guisarme']['code'] = 'w95'
craft['guisarme']['type'] = 'craft'
craft['guisarme']['guild'] = 1

craft['meteor bow'] = defaultdict(dict)
craft['meteor bow']['recipe']['artisan mold'] = 2
craft['meteor bow']['recipe']['coke'] = 103
craft['meteor bow']['recipe']['hardener'] = 7
craft['meteor bow']['recipe']['ruby'] = 3
craft['meteor bow']['recipe']['wooden shaft'] = 97
craft['meteor bow']['recipe']['silver frame'] = 21
craft['meteor bow']['recipe']['quality cloth'] = 5
craft['meteor bow']['recipe']['meteor bow recipe'] = 1
craft['meteor bow']['recipe']['meteor bow part'] = 6
craft['meteor bow']['code'] = 'w96'
craft['meteor bow']['type'] = 'craft'
craft['meteor bow']['guild'] = 1

craft['nightfall bow'] = defaultdict(dict)
craft['nightfall bow']['recipe']['artisan mold'] = 2
craft['nightfall bow']['recipe']['coke'] = 103
craft['nightfall bow']['recipe']['hardener'] = 7
craft['nightfall bow']['recipe']['sapphire'] = 3
craft['nightfall bow']['recipe']['wooden shaft'] = 97
craft['nightfall bow']['recipe']['steel mold'] = 91
craft['nightfall bow']['recipe']['quality cloth'] = 5
craft['nightfall bow']['recipe']['nightfall bow recipe'] = 1
craft['nightfall bow']['recipe']['nightfall bow part'] = 6
craft['nightfall bow']['code'] = 'w97'
craft['nightfall bow']['type'] = 'craft'
craft['nightfall bow']['guild'] = 1

craft['black morningstar'] = defaultdict(dict)
craft['black morningstar']['recipe']['artisan mold'] = 4
craft['black morningstar']['recipe']['coke'] = 107
craft['black morningstar']['recipe']['hardener'] = 6
craft['black morningstar']['recipe']['ruby'] = 3
craft['black morningstar']['recipe']['metal plate'] = 79
craft['black morningstar']['recipe']['silver frame'] = 17
craft['black morningstar']['recipe']['quality cloth'] = 3
craft['black morningstar']['recipe']['black morningstar recipe'] = 1
craft['black morningstar']['recipe']['black morningstar part'] = 6
craft['black morningstar']['code'] = 'w98'
craft['black morningstar']['type'] = 'craft'
craft['black morningstar']['guild'] = 1

craft['maiming bulawa'] = defaultdict(dict)
craft['maiming bulawa']['recipe']['artisan mold'] = 4
craft['maiming bulawa']['recipe']['coke'] = 107
craft['maiming bulawa']['recipe']['hardener'] = 6
craft['maiming bulawa']['recipe']['sapphire'] = 3
craft['maiming bulawa']['recipe']['metal plate'] = 79
craft['maiming bulawa']['recipe']['silver frame'] = 7
craft['maiming bulawa']['recipe']['steel mold'] = 39
craft['maiming bulawa']['recipe']['quality cloth'] = 1
craft['maiming bulawa']['recipe']['maiming bulawa recipe'] = 1
craft['maiming bulawa']['recipe']['maiming bulawa part'] = 6
craft['maiming bulawa']['code'] = 'w99'
craft['maiming bulawa']['type'] = 'craft'
craft['maiming bulawa']['guild'] = 1

craft['council shield'] = defaultdict(dict)
craft['council shield']['recipe']['blacksmith mold'] = 3
craft['council shield']['recipe']['coke'] = 15
craft['council shield']['recipe']['solvent'] = 6
craft['council shield']['recipe']['sapphire'] = 1
craft['council shield']['recipe']['metal plate'] = 17
craft['council shield']['recipe']['silver alloy'] = 29
craft['council shield']['recipe']['quality cloth'] = 2
craft['council shield']['recipe']['council shield recipe'] = 1
craft['council shield']['recipe']['council shield part'] = 6
craft['council shield']['code'] = 'a82'
craft['council shield']['type'] = 'craft'
craft['council shield']['guild'] = 1

craft['griffin knife'] = defaultdict(dict)
craft['griffin knife']['recipe']['coke'] = 27
craft['griffin knife']['recipe']['silver alloy'] = 21
craft['griffin knife']['recipe']['quality cloth'] = 2
craft['griffin knife']['recipe']['ruby'] = 1
craft['griffin knife']['recipe']['magic stone'] = 1
craft['griffin knife']['recipe']['artisan mold'] = 1
craft['griffin knife']['recipe']['blacksmith mold'] = 1
craft['griffin knife']['recipe']['metal plate'] = 11
craft['griffin knife']['recipe']['hardener'] = 3
craft['griffin knife']['recipe']['griffin knife recipe'] = 1
craft['griffin knife']['recipe']['griffin knife part'] = 5
craft['griffin knife']['code'] = 'w91'
craft['griffin knife']['type'] = 'craft'
craft['griffin knife']['guild'] = 1

craft['council helmet'] = defaultdict(dict)
craft['council helmet']['recipe']['metallic fiber'] = 29
craft['council helmet']['recipe']['quality cloth'] = 2
craft['council helmet']['recipe']['blacksmith mold'] = 3
craft['council helmet']['recipe']['rope'] = 17
craft['council helmet']['recipe']['coke'] = 13
craft['council helmet']['recipe']['solvent'] = 9
craft['council helmet']['recipe']['sapphire'] = 5
craft['council helmet']['recipe']['council helmet recipe'] = 1
craft['council helmet']['recipe']['council helmet part'] = 6
craft['council helmet']['code'] = 'a79'
craft['council helmet']['type'] = 'craft'
craft['council helmet']['guild'] = 1

craft['griffin helmet'] = defaultdict(dict)
craft['griffin helmet']['recipe']['solvent'] = 8
craft['griffin helmet']['recipe']['blacksmith mold'] = 3
craft['griffin helmet']['recipe']['coke'] = 11
craft['griffin helmet']['recipe']['ruby'] = 5
craft['griffin helmet']['recipe']['rope'] = 15
craft['griffin helmet']['recipe']['crafted leather'] = 14
craft['griffin helmet']['recipe']['quality cloth'] = 7
craft['griffin helmet']['recipe']['griffin helmet recipe'] = 1
craft['griffin helmet']['recipe']['griffin helmet part'] = 6
craft['griffin helmet']['code'] = 'a84'
craft['griffin helmet']['type'] = 'craft'
craft['griffin helmet']['guild'] = 1

craft['celestial helmet'] = defaultdict(dict)
craft['celestial helmet']['recipe']['ruby'] = 1
craft['celestial helmet']['recipe']['rope'] = 11
craft['celestial helmet']['recipe']['crafted leather'] = 14
craft['celestial helmet']['recipe']['quality cloth'] = 9
craft['celestial helmet']['recipe']['coke'] = 11
craft['celestial helmet']['recipe']['blacksmith mold'] = 1
craft['celestial helmet']['recipe']['solvent'] = 3
craft['celestial helmet']['recipe']['magic stone'] = 9
craft['celestial helmet']['recipe']['sapphire'] = 1
craft['celestial helmet']['recipe']['celestial helmet recipe'] = 1
craft['celestial helmet']['recipe']['celestial helmet part'] = 6
craft['celestial helmet']['code'] = 'a88'
craft['celestial helmet']['type'] = 'craft'
craft['celestial helmet']['guild'] = 1

craft['council armor'] = defaultdict(dict)
craft['council armor']['recipe']['rope'] = 25
craft['council armor']['recipe']['coke'] = 23
craft['council armor']['recipe']['solvent'] = 18
craft['council armor']['recipe']['crafted leather'] = 3
craft['council armor']['recipe']['sapphire'] = 6
craft['council armor']['recipe']['quality cloth'] = 11
craft['council armor']['recipe']['blacksmith mold'] = 5
craft['council armor']['recipe']['metallic fiber'] = 30
craft['council armor']['recipe']['council armor recipe'] = 1
craft['council armor']['recipe']['council armor part'] = 6
craft['council armor']['code'] = 'a78'
craft['council armor']['type'] = 'craft'
craft['council armor']['guild'] = 1

craft['griffin armor'] = defaultdict(dict)
craft['griffin armor']['recipe']['blacksmith mold'] = 4
craft['griffin armor']['recipe']['crafted leather'] = 14
craft['griffin armor']['recipe']['quality cloth'] = 11
craft['griffin armor']['recipe']['rope'] = 17
craft['griffin armor']['recipe']['coke'] = 19
craft['griffin armor']['recipe']['solvent'] = 15
craft['griffin armor']['recipe']['ruby'] = 7
craft['griffin armor']['recipe']['griffin armor recipe'] = 1
craft['griffin armor']['recipe']['griffin armor part'] = 6
craft['griffin armor']['code'] = 'a83'
craft['griffin armor']['type'] = 'craft'
craft['griffin armor']['guild'] = 1

craft['celestial armor'] = defaultdict(dict)
craft['celestial armor']['recipe']['blacksmith mold'] = 2
craft['celestial armor']['recipe']['magic stone'] = 15
craft['celestial armor']['recipe']['sapphire'] = 2
craft['celestial armor']['recipe']['quality cloth'] = 18
craft['celestial armor']['recipe']['solvent'] = 21
craft['celestial armor']['recipe']['ruby'] = 2
craft['celestial armor']['recipe']['crafted leather'] = 17
craft['celestial armor']['recipe']['celestial armor recipe'] = 1
craft['celestial armor']['recipe']['celestial armor part'] = 6
craft['celestial armor']['code'] = 'a87'
craft['celestial armor']['type'] = 'craft'
craft['celestial armor']['guild'] = 1

craft['council gauntlets'] = defaultdict(dict)
craft['council gauntlets']['recipe']['rope'] = 9
craft['council gauntlets']['recipe']['sapphire'] = 1
craft['council gauntlets']['recipe']['quality cloth'] = 2
craft['council gauntlets']['recipe']['metallic fiber'] = 21
craft['council gauntlets']['recipe']['coke'] = 11
craft['council gauntlets']['recipe']['solvent'] = 3
craft['council gauntlets']['recipe']['blacksmith mold'] = 1
craft['council gauntlets']['recipe']['council gauntlets recipe'] = 1
craft['council gauntlets']['recipe']['council gauntlets part'] = 6
craft['council gauntlets']['code'] = 'a81'
craft['council gauntlets']['type'] = 'craft'
craft['council gauntlets']['guild'] = 1

craft['griffin gloves'] = defaultdict(dict)
craft['griffin gloves']['recipe']['crafted leather'] = 13
craft['griffin gloves']['recipe']['quality cloth'] = 5
craft['griffin gloves']['recipe']['coke'] = 9
craft['griffin gloves']['recipe']['rope'] = 7
craft['griffin gloves']['recipe']['blacksmith mold'] = 1
craft['griffin gloves']['recipe']['solvent'] = 3
craft['griffin gloves']['recipe']['ruby'] = 1
craft['griffin gloves']['recipe']['griffin gloves recipe'] = 1
craft['griffin gloves']['recipe']['griffin gloves part'] = 6
craft['griffin gloves']['code'] = 'a86'
craft['griffin gloves']['type'] = 'craft'
craft['griffin gloves']['guild'] = 1

craft['celestial bracers'] = defaultdict(dict)
craft['celestial bracers']['recipe']['rope'] = 7
craft['celestial bracers']['recipe']['coke'] = 9
craft['celestial bracers']['recipe']['magic stone'] = 3
craft['celestial bracers']['recipe']['ruby'] = 1
craft['celestial bracers']['recipe']['sapphire'] = 1
craft['celestial bracers']['recipe']['blacksmith mold'] = 1
craft['celestial bracers']['recipe']['crafted leather'] = 11
craft['celestial bracers']['recipe']['quality cloth'] = 11
craft['celestial bracers']['recipe']['solvent'] = 3
craft['celestial bracers']['recipe']['celestial bracers recipe'] = 1
craft['celestial bracers']['recipe']['celestial bracers part'] = 6
craft['celestial bracers']['code'] = 'a90'
craft['celestial bracers']['type'] = 'craft'
craft['celestial bracers']['guild'] = 1

craft['council boots'] = defaultdict(dict)
craft['council boots']['recipe']['coke'] = 11
craft['council boots']['recipe']['sapphire'] = 2
craft['council boots']['recipe']['quality cloth'] = 5
craft['council boots']['recipe']['blacksmith mold'] = 1
craft['council boots']['recipe']['rope'] = 9
craft['council boots']['recipe']['metallic fiber'] = 21
craft['council boots']['recipe']['solvent'] = 3
craft['council boots']['recipe']['council boots recipe'] = 1
craft['council boots']['recipe']['council boots part'] = 6
craft['council boots']['code'] = 'a80'
craft['council boots']['type'] = 'craft'
craft['council boots']['guild'] = 1

craft['griffin boots'] = defaultdict(dict)
craft['griffin boots']['recipe']['rope'] = 6
craft['griffin boots']['recipe']['ruby'] = 2
craft['griffin boots']['recipe']['blacksmith mold'] = 2
craft['griffin boots']['recipe']['crafted leather'] = 14
craft['griffin boots']['recipe']['coke'] = 9
craft['griffin boots']['recipe']['solvent'] = 5
craft['griffin boots']['recipe']['quality cloth'] = 5
craft['griffin boots']['recipe']['griffin boots recipe'] = 1
craft['griffin boots']['recipe']['griffin boots part'] = 6
craft['griffin boots']['code'] = 'a85'
craft['griffin boots']['type'] = 'craft'
craft['griffin boots']['guild'] = 1

craft['celestial boots'] = defaultdict(dict)
craft['celestial boots']['recipe']['blacksmith mold'] = 1
craft['celestial boots']['recipe']['crafted leather'] = 13
craft['celestial boots']['recipe']['solvent'] = 3
craft['celestial boots']['recipe']['magic stone'] = 3
craft['celestial boots']['recipe']['ruby'] = 2
craft['celestial boots']['recipe']['sapphire'] = 2
craft['celestial boots']['recipe']['rope'] = 6
craft['celestial boots']['recipe']['quality cloth'] = 9
craft['celestial boots']['recipe']['coke'] = 9
craft['celestial boots']['recipe']['celestial boots recipe'] = 1
craft['celestial boots']['recipe']['celestial boots part'] = 6
craft['celestial boots']['code'] = 'a89'
craft['celestial boots']['type'] = 'craft'
craft['celestial boots']['guild'] = 1

craft['assault cape'] = defaultdict(dict)
craft['assault cape']['recipe']['blacksmith mold'] = 1
craft['assault cape']['recipe']['rope'] = 3
craft['assault cape']['recipe']['quality cloth'] = 13
craft['assault cape']['recipe']['coke'] = 11
craft['assault cape']['recipe']['solvent'] = 4
craft['assault cape']['recipe']['sapphire'] = 1
craft['assault cape']['recipe']['assault cape recipe'] = 1
craft['assault cape']['recipe']['assault cape part'] = 4
craft['assault cape']['code'] = 'a100'
craft['assault cape']['type'] = 'craft'
craft['assault cape']['guild'] = 1

craft['craftsman apron'] = defaultdict(dict)
craft['craftsman apron']['recipe']['artisan mold'] = 1
craft['craftsman apron']['recipe']['rope'] = 2
craft['craftsman apron']['recipe']['crafted leather'] = 17
craft['craftsman apron']['recipe']['quality cloth'] = 3
craft['craftsman apron']['recipe']['coke'] = 11
craft['craftsman apron']['recipe']['solvent'] = 1
craft['craftsman apron']['recipe']['craftsman apron recipe'] = 1
craft['craftsman apron']['recipe']['craftsman apron part'] = 4
craft['craftsman apron']['code'] = 'a101'
craft['craftsman apron']['type'] = 'craft'
craft['craftsman apron']['guild'] = 1

craft['stoneskin cloak'] = defaultdict(dict)
craft['stoneskin cloak']['recipe']['solvent'] = 1
craft['stoneskin cloak']['recipe']['blacksmith mold'] = 2
craft['stoneskin cloak']['recipe']['rope'] = 17
craft['stoneskin cloak']['recipe']['crafted leather'] = 3
craft['stoneskin cloak']['recipe']['quality cloth'] = 11
craft['stoneskin cloak']['recipe']['coke'] = 1
craft['stoneskin cloak']['recipe']['silver alloy'] = 1
craft['stoneskin cloak']['recipe']['stoneskin cloak recipe'] = 1
craft['stoneskin cloak']['recipe']['stoneskin cloak part'] = 4
craft['stoneskin cloak']['code'] = 'a103'
craft['stoneskin cloak']['type'] = 'craft'
craft['stoneskin cloak']['guild'] = 1

# t5
craft['brutalizer flail'] = defaultdict(dict)
craft['brutalizer flail']['recipe']['brutalizer flail recipe'] = 1
craft['brutalizer flail']['recipe']['brutalizer flail part'] = 9
craft['brutalizer flail']['recipe']['blacksmith frame'] = 6
craft['brutalizer flail']['recipe']['coke'] = 157
craft['brutalizer flail']['recipe']['metal plate'] = 79
craft['brutalizer flail']['recipe']['silver frame'] = 10
craft['brutalizer flail']['recipe']['silver mold'] = 39
craft['brutalizer flail']['recipe']['quality cloth'] = 3
craft['brutalizer flail']['code'] = 'w111'
craft['brutalizer flail']['type'] = 'craft'
craft['brutalizer flail']['guild'] = 1

craft['decimation harpoon'] = defaultdict(dict)
craft['decimation harpoon']['recipe']['silver mold'] = 11
craft['decimation harpoon']['recipe']['quality cloth'] = 3
craft['decimation harpoon']['recipe']['artisan frame'] = 4
craft['decimation harpoon']['recipe']['blacksmith frame'] = 4
craft['decimation harpoon']['recipe']['coke'] = 122
craft['decimation harpoon']['recipe']['wooden shaft'] = 99
craft['decimation harpoon']['recipe']['silver frame'] = 21
craft['decimation harpoon']['recipe']['hardener'] = 8
craft['decimation harpoon']['recipe']['decimation harpoon recipe'] = 1
craft['decimation harpoon']['recipe']['decimation harpoon part'] = 8
craft['decimation harpoon']['code'] = 'w106'
craft['decimation harpoon']['type'] = 'craft'
craft['decimation harpoon']['guild'] = 1

craft['discarnate bracers'] = defaultdict(dict)
craft['discarnate bracers']['recipe']['string'] = 7
craft['discarnate bracers']['recipe']['quality cloth'] = 2
craft['discarnate bracers']['recipe']['silver mold'] = 7
craft['discarnate bracers']['recipe']['ruby'] = 15
craft['discarnate bracers']['recipe']['sapphire'] = 10
craft['discarnate bracers']['recipe']['discarnate bracers recipe'] = 1
craft['discarnate bracers']['recipe']['discarnate bracers part'] = 8
craft['discarnate bracers']['recipe']['artisan mold'] = 2
craft['discarnate bracers']['recipe']['bone powder'] = 11
craft['discarnate bracers']['recipe']['crafted leather'] = 11
craft['discarnate bracers']['recipe']['solvent'] = 2
craft['discarnate bracers']['code'] = 'a111'
craft['discarnate bracers']['type'] = 'craft'
craft['discarnate bracers']['guild'] = 1

craft['discarnate circlet'] = defaultdict(dict)
craft['discarnate circlet']['recipe']['silver mold'] = 12
craft['discarnate circlet']['recipe']['sapphire'] = 17
craft['discarnate circlet']['recipe']['discarnate circlet part'] = 8
craft['discarnate circlet']['recipe']['artisan mold'] = 2
craft['discarnate circlet']['recipe']['bone powder'] = 5
craft['discarnate circlet']['recipe']['crafted leather'] = 1
craft['discarnate circlet']['recipe']['ruby'] = 20
craft['discarnate circlet']['recipe']['discarnate circlet recipe'] = 1
craft['discarnate circlet']['recipe']['string'] = 31
craft['discarnate circlet']['recipe']['quality cloth'] = 9
craft['discarnate circlet']['recipe']['solvent'] = 1
craft['discarnate circlet']['code'] = 'a108'
craft['discarnate circlet']['type'] = 'craft'
craft['discarnate circlet']['guild'] = 1

craft['discarnate robe'] = defaultdict(dict)
craft['discarnate robe']['recipe']['artisan mold'] = 3
craft['discarnate robe']['recipe']['silver mold'] = 17
craft['discarnate robe']['recipe']['ruby'] = 30
craft['discarnate robe']['recipe']['sapphire'] = 20
craft['discarnate robe']['recipe']['discarnate robe recipe'] = 1
craft['discarnate robe']['recipe']['discarnate robe part'] = 8
craft['discarnate robe']['recipe']['bone powder'] = 15
craft['discarnate robe']['recipe']['quality cloth'] = 11
craft['discarnate robe']['code'] = 'a105'
craft['discarnate robe']['type'] = 'craft'
craft['discarnate robe']['guild'] = 1

craft['discarnate shoes'] = defaultdict(dict)
craft['discarnate shoes']['recipe']['discarnate shoes part'] = 8
craft['discarnate shoes']['recipe']['solvent'] = 1
craft['discarnate shoes']['recipe']['sapphire'] = 5
craft['discarnate shoes']['recipe']['silver mold'] = 2
craft['discarnate shoes']['recipe']['bone powder'] = 20
craft['discarnate shoes']['recipe']['ruby'] = 10
craft['discarnate shoes']['recipe']['discarnate shoes recipe'] = 1
craft['discarnate shoes']['recipe']['artisan mold'] = 3
craft['discarnate shoes']['recipe']['string'] = 11
craft['discarnate shoes']['recipe']['quality cloth'] = 3
craft['discarnate shoes']['code'] = 'a116'
craft['discarnate shoes']['type'] = 'craft'
craft['discarnate shoes']['guild'] = 1

craft['doom warglaive'] = defaultdict(dict)
craft['doom warglaive']['recipe']['blacksmith frame'] = 7
craft['doom warglaive']['recipe']['metal plate'] = 79
craft['doom warglaive']['recipe']['silver frame'] = 27
craft['doom warglaive']['recipe']['hardener'] = 5
craft['doom warglaive']['recipe']['sapphire'] = 1
craft['doom warglaive']['recipe']['doom warglaive recipe'] = 1
craft['doom warglaive']['recipe']['doom warglaive part'] = 9
craft['doom warglaive']['recipe']['coke'] = 100
craft['doom warglaive']['recipe']['quality cloth'] = 4
craft['doom warglaive']['recipe']['cord'] = 28
craft['doom warglaive']['code'] = 'w102'
craft['doom warglaive']['type'] = 'craft'
craft['doom warglaive']['guild'] = 1

craft['heartstriker bow'] = defaultdict(dict)
craft['heartstriker bow']['recipe']['heartstriker bow part'] = 7
craft['heartstriker bow']['recipe']['artisan mold'] = 2
craft['heartstriker bow']['recipe']['coke'] = 103
craft['heartstriker bow']['recipe']['wooden shaft'] = 137
craft['heartstriker bow']['recipe']['silver frame'] = 21
craft['heartstriker bow']['recipe']['hardener'] = 7
craft['heartstriker bow']['recipe']['quality cloth'] = 6
craft['heartstriker bow']['recipe']['heartstriker bow recipe'] = 1
craft['heartstriker bow']['code'] = 'w105'
craft['heartstriker bow']['type'] = 'craft'
craft['heartstriker bow']['guild'] = 1

craft['lightbane katana'] = defaultdict(dict)
craft['lightbane katana']['recipe']['artisan mold'] = 4
craft['lightbane katana']['recipe']['silver frame'] = 13
craft['lightbane katana']['recipe']['ruby'] = 1
craft['lightbane katana']['recipe']['lightbane katana recipe'] = 1
craft['lightbane katana']['recipe']['lightbane katana part'] = 8
craft['lightbane katana']['recipe']['coke'] = 122
craft['lightbane katana']['recipe']['quality cloth'] = 3
craft['lightbane katana']['recipe']['metal plate'] = 79
craft['lightbane katana']['recipe']['cord'] = 25
craft['lightbane katana']['recipe']['hardener'] = 7
craft['lightbane katana']['code'] = 'w101'
craft['lightbane katana']['type'] = 'craft'
craft['lightbane katana']['guild'] = 1

craft['malificent maul'] = defaultdict(dict)
craft['malificent maul']['recipe']['quality cloth'] = 4
craft['malificent maul']['recipe']['malificent maul recipe'] = 1
craft['malificent maul']['recipe']['malificent maul part'] = 7
craft['malificent maul']['recipe']['silver mold'] = 59
craft['malificent maul']['recipe']['coke'] = 137
craft['malificent maul']['recipe']['metal plate'] = 79
craft['malificent maul']['recipe']['silver frame'] = 12
craft['malificent maul']['recipe']['hardener'] = 16
craft['malificent maul']['code'] = 'w107'
craft['malificent maul']['type'] = 'craft'
craft['malificent maul']['guild'] = 1

craft['manticore armor'] = defaultdict(dict)
craft['manticore armor']['recipe']['bone powder'] = 13
craft['manticore armor']['recipe']['sapphire'] = 5
craft['manticore armor']['recipe']['manticore armor recipe'] = 1
craft['manticore armor']['recipe']['manticore armor part'] = 8
craft['manticore armor']['recipe']['quality cloth'] = 15
craft['manticore armor']['recipe']['artisan mold'] = 2
craft['manticore armor']['recipe']['silver mold'] = 25
craft['manticore armor']['recipe']['steel mold'] = 5
craft['manticore armor']['recipe']['ruby'] = 15
craft['manticore armor']['code'] = 'a103'
craft['manticore armor']['type'] = 'craft'
craft['manticore armor']['guild'] = 1

craft['manticore boots'] = defaultdict(dict)
craft['manticore boots']['recipe']['sapphire'] = 2
craft['manticore boots']['recipe']['manticore boots recipe'] = 1
craft['manticore boots']['recipe']['manticore boots part'] = 8
craft['manticore boots']['recipe']['artisan mold'] = 1
craft['manticore boots']['recipe']['string'] = 6
craft['manticore boots']['recipe']['silver mold'] = 6
craft['manticore boots']['recipe']['ruby'] = 8
craft['manticore boots']['recipe']['rope'] = 3
craft['manticore boots']['recipe']['quality cloth'] = 7
craft['manticore boots']['recipe']['crafted leather'] = 15
craft['manticore boots']['recipe']['solvent'] = 1
craft['manticore boots']['code'] = 'a114'
craft['manticore boots']['type'] = 'craft'
craft['manticore boots']['guild'] = 1

craft['manticore gloves'] = defaultdict(dict)
craft['manticore gloves']['recipe']['string'] = 7
craft['manticore gloves']['recipe']['solvent'] = 2
craft['manticore gloves']['recipe']['ruby'] = 9
craft['manticore gloves']['recipe']['sapphire'] = 1
craft['manticore gloves']['recipe']['manticore gloves recipe'] = 1
craft['manticore gloves']['recipe']['artisan mold'] = 1
craft['manticore gloves']['recipe']['rope'] = 4
craft['manticore gloves']['recipe']['silver mold'] = 11
craft['manticore gloves']['recipe']['manticore gloves part'] = 8
craft['manticore gloves']['recipe']['crafted leather'] = 11
craft['manticore gloves']['recipe']['quality cloth'] = 3
craft['manticore gloves']['code'] = 'a109'
craft['manticore gloves']['type'] = 'craft'
craft['manticore gloves']['guild'] = 1

craft['manticore helmet'] = defaultdict(dict)
craft['manticore helmet']['recipe']['manticore helmet part'] = 8
craft['manticore helmet']['recipe']['string'] = 21
craft['manticore helmet']['recipe']['crafted leather'] = 17
craft['manticore helmet']['recipe']['quality cloth'] = 3
craft['manticore helmet']['recipe']['silver mold'] = 11
craft['manticore helmet']['recipe']['ruby'] = 9
craft['manticore helmet']['recipe']['manticore helmet recipe'] = 1
craft['manticore helmet']['recipe']['artisan mold'] = 1
craft['manticore helmet']['recipe']['bone powder'] = 9
craft['manticore helmet']['recipe']['solvent'] = 2
craft['manticore helmet']['recipe']['sapphire'] = 1
craft['manticore helmet']['code'] = 'a106'
craft['manticore helmet']['type'] = 'craft'
craft['manticore helmet']['guild'] = 1

craft['overseer armor'] = defaultdict(dict)
craft['overseer armor']['recipe']['bone powder'] = 15
craft['overseer armor']['recipe']['quality cloth'] = 3
craft['overseer armor']['recipe']['blacksmith mold'] = 4
craft['overseer armor']['recipe']['steel mold'] = 17
craft['overseer armor']['recipe']['overseer armor recipe'] = 1
craft['overseer armor']['recipe']['overseer armor part'] = 8
craft['overseer armor']['recipe']['silver mold'] = 3
craft['overseer armor']['recipe']['ruby'] = 3
craft['overseer armor']['recipe']['sapphire'] = 10
craft['overseer armor']['code'] = 'a104'
craft['overseer armor']['type'] = 'craft'
craft['overseer armor']['guild'] = 1

craft['overseer boots'] = defaultdict(dict)
craft['overseer boots']['recipe']['blacksmith mold'] = 2
craft['overseer boots']['recipe']['string'] = 6
craft['overseer boots']['recipe']['steel mold'] = 6
craft['overseer boots']['recipe']['solvent'] = 3
craft['overseer boots']['recipe']['ruby'] = 1
craft['overseer boots']['recipe']['overseer boots recipe'] = 1
craft['overseer boots']['recipe']['overseer boots part'] = 8
craft['overseer boots']['recipe']['rope'] = 1
craft['overseer boots']['recipe']['quality cloth'] = 2
craft['overseer boots']['recipe']['crafted leather'] = 11
craft['overseer boots']['recipe']['sapphire'] = 8
craft['overseer boots']['code'] = 'a115'
craft['overseer boots']['type'] = 'craft'
craft['overseer boots']['guild'] = 1

craft['overseer gauntlets'] = defaultdict(dict)
craft['overseer gauntlets']['recipe']['rope'] = 3
craft['overseer gauntlets']['recipe']['string'] = 15
craft['overseer gauntlets']['recipe']['steel mold'] = 13
craft['overseer gauntlets']['recipe']['ruby'] = 1
craft['overseer gauntlets']['recipe']['sapphire'] = 9
craft['overseer gauntlets']['recipe']['overseer gauntlets recipe'] = 1
craft['overseer gauntlets']['recipe']['overseer gauntlets part'] = 8
craft['overseer gauntlets']['recipe']['blacksmith mold'] = 2
craft['overseer gauntlets']['recipe']['crafted leather'] = 7
craft['overseer gauntlets']['recipe']['quality cloth'] = 1
craft['overseer gauntlets']['recipe']['solvent'] = 2
craft['overseer gauntlets']['code'] = 'a110'
craft['overseer gauntlets']['type'] = 'craft'
craft['overseer gauntlets']['guild'] = 1

craft['overseer helmet'] = defaultdict(dict)
craft['overseer helmet']['recipe']['steel mold'] = 13
craft['overseer helmet']['recipe']['solvent'] = 4
craft['overseer helmet']['recipe']['ruby'] = 1
craft['overseer helmet']['recipe']['overseer helmet recipe'] = 1
craft['overseer helmet']['recipe']['string'] = 21
craft['overseer helmet']['recipe']['bone powder'] = 15
craft['overseer helmet']['recipe']['crafted leather'] = 6
craft['overseer helmet']['recipe']['overseer helmet part'] = 8
craft['overseer helmet']['recipe']['blacksmith mold'] = 2
craft['overseer helmet']['recipe']['quality cloth'] = 1
craft['overseer helmet']['recipe']['sapphire'] = 9
craft['overseer helmet']['code'] = 'a107'
craft['overseer helmet']['type'] = 'craft'
craft['overseer helmet']['guild'] = 1

craft['overseer shield'] = defaultdict(dict)
craft['overseer shield']['recipe']['overseer shield part'] = 8
craft['overseer shield']['recipe']['blacksmith mold'] = 5
craft['overseer shield']['recipe']['metal plate'] = 17
craft['overseer shield']['recipe']['steel mold'] = 14
craft['overseer shield']['recipe']['solvent'] = 3
craft['overseer shield']['recipe']['bone powder'] = 7
craft['overseer shield']['recipe']['sapphire'] = 3
craft['overseer shield']['recipe']['overseer shield recipe'] = 1
craft['overseer shield']['code'] = 'a113'
craft['overseer shield']['type'] = 'craft'
craft['overseer shield']['guild'] = 1

craft['poniard'] = defaultdict(dict)
craft['poniard']['recipe']['silver frame'] = 3
craft['poniard']['recipe']['quality cloth'] = 2
craft['poniard']['recipe']['poniard recipe'] = 1
craft['poniard']['recipe']['poniard part'] = 5
craft['poniard']['recipe']['artisan mold'] = 3
craft['poniard']['recipe']['coke'] = 20
craft['poniard']['recipe']['metal plate'] = 13
craft['poniard']['recipe']['silver alloy'] = 25
craft['poniard']['code'] = 'w100'
craft['poniard']['type'] = 'craft'
craft['poniard']['guild'] = 1

craft['sinister ranseur'] = defaultdict(dict)
craft['sinister ranseur']['recipe']['quality cloth'] = 4
craft['sinister ranseur']['recipe']['ruby'] = 1
craft['sinister ranseur']['recipe']['sinister ranseur part'] = 9
craft['sinister ranseur']['recipe']['wooden shaft'] = 99
craft['sinister ranseur']['recipe']['silver frame'] = 9
craft['sinister ranseur']['recipe']['silver mold'] = 9
craft['sinister ranseur']['recipe']['steel mold'] = 33
craft['sinister ranseur']['recipe']['hardener'] = 11
craft['sinister ranseur']['recipe']['sinister ranseur recipe'] = 1
craft['sinister ranseur']['recipe']['artisan mold'] = 5
craft['sinister ranseur']['recipe']['coke'] = 50
craft['sinister ranseur']['code'] = 'w104'
craft['sinister ranseur']['type'] = 'craft'
craft['sinister ranseur']['guild'] = 1

craft['windstalker bow'] = defaultdict(dict)
craft['windstalker bow']['recipe']['windstalker bow part'] = 9
craft['windstalker bow']['recipe']['blacksmith frame'] = 19
craft['windstalker bow']['recipe']['coke'] = 83
craft['windstalker bow']['recipe']['wooden shaft'] = 112
craft['windstalker bow']['recipe']['silver mold'] = 41
craft['windstalker bow']['recipe']['hardener'] = 7
craft['windstalker bow']['recipe']['quality cloth'] = 6
craft['windstalker bow']['recipe']['windstalker bow recipe'] = 1
craft['windstalker bow']['code'] = 'w106'
craft['windstalker bow']['type'] = 'craft'
craft['windstalker bow']['guild'] = 1

craft['piercing arrows pack'] = defaultdict(dict)
craft['piercing arrows pack']['recipe']['stick'] = 9
craft['piercing arrows pack']['recipe']['steel'] = 6
craft['piercing arrows pack']['recipe']['quality cloth'] = 1
craft['piercing arrows pack']['recipe']['coke'] = 1
craft['piercing arrows pack']['code'] = '520'
craft['piercing arrows pack']['type'] = 'craft'
craft['piercing arrows pack']['guild'] = 1

craft['bodkin arrows pack'] = defaultdict(dict)
craft['bodkin arrows pack']['recipe']['stick'] = 9
craft['bodkin arrows pack']['recipe']['silver ore'] = 6
craft['bodkin arrows pack']['recipe']['steel'] = 4
craft['bodkin arrows pack']['recipe']['bone powder'] = 1
craft['bodkin arrows pack']['recipe']['coke'] = 1
craft['bodkin arrows pack']['recipe']['quality cloth'] = 1
craft['bodkin arrows pack']['code'] = '523'
craft['bodkin arrows pack']['type'] = 'craft'
craft['bodkin arrows pack']['guild'] = 1

craft['mechblade arrows pack'] = defaultdict(dict)
craft['mechblade arrows pack']['recipe']['stick'] = 9
craft['mechblade arrows pack']['recipe']['steel'] = 5
craft['mechblade arrows pack']['recipe']['bone powder'] = 2
craft['mechblade arrows pack']['recipe']['quality cloth'] = 1
craft['mechblade arrows pack']['recipe']['coke'] = 1
craft['mechblade arrows pack']['code'] = '525'
craft['mechblade arrows pack']['type'] = 'craft'
craft['mechblade arrows pack']['guild'] = 1
